In [12]:
import cv2
import pickle
import tensorflow
import numpy as np
from numpy.linalg import norm
from tensorflow.keras.preprocessing import image
from tensorflow.keras.layers import GlobalMaxPooling2D
from tensorflow.keras.applications.resnet50 import ResNet50,preprocess_input
from sklearn.neighbors import NearestNeighbors

In [5]:
feature_list = np.array(pickle.load(open('embeddings.pkl','rb')))
filenames = pickle.load(open('filenames.pkl','rb'))

In [9]:
model = ResNet50(weights='imagenet',include_top=False,input_shape=(224,224,3))
model.trainable=False

In [13]:
model = tensorflow.keras.Sequential([
    model,
    GlobalMaxPooling2D()
])

In [16]:
img = image.load_img('sample/1163.jpg',target_size=(224,224))
img_array = image.img_to_array(img)
img_array

array([[[255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.],
        ...,
        [255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.]],

       [[255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.],
        ...,
        [255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.]],

       [[255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.],
        ...,
        [255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.]],

       ...,

       [[255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.],
        ...,
        [255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.]],

       [[255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.],
        ...,
        [255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.]],

       [[255., 255., 255.],
        [255., 255., 255.],
        [255., 2

In [18]:
expanded_img_array = np.expand_dims(img_array,axis=0)
expanded_img_array

array([[[[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        [[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        [[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        ...,

        [[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        [[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        [[255., 255., 255.],
       

In [19]:
preprocessed_img = preprocess_input(expanded_img_array)
preprocessed_img

array([[[[151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         ...,
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ]],

        [[151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         ...,
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ]],

        [[151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         ...,
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ]],

        ...,

        [[151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         ...,


In [20]:
result = model.predict(preprocessed_img).flatten()
result

1/1 [==============================] - 1s 772ms/step


array([ 1.635139 , 19.32439  ,  1.8080466, ...,  1.1685896, 17.437454 ,
       12.0990305], dtype=float32)

In [21]:
normalized_result = result / norm(result)
normalized_result

array([0.00491867, 0.05812978, 0.00543879, ..., 0.00351524, 0.05245368,
       0.03639515], dtype=float32)

In [23]:
import pandas as pd
pd.DataFrame(feature_list)

0         1         2         3         4         5         6     \
0    0.000000  0.017616  0.001716  0.008088  0.025890  0.012527  0.014420   
1    0.000000  0.036489  0.000000  0.004160  0.032850  0.006727  0.055993   
2    0.000000  0.036421  0.007104  0.000000  0.029179  0.002221  0.071871   
3    0.002322  0.050305  0.007477  0.002382  0.019975  0.009069  0.021270   
4    0.003068  0.062405  0.000000  0.031615  0.040178  0.000025  0.021961   
..        ...       ...       ...       ...       ...       ...       ...   
495  0.000000  0.006391  0.005002  0.012008  0.026491  0.016889  0.018968   
496  0.000000  0.004967  0.012339  0.008322  0.011168  0.007148  0.004477   
497  0.005085  0.013133  0.000000  0.021698  0.022575  0.005280  0.012228   
498  0.025089  0.011451  0.001956  0.040311  0.011278  0.003555  0.007564   
499  0.001065  0.001095  0.007315  0.004014  0.000000  0.000000  0.063224   

         7         8         9     ...      2038      2039      2040  \
0    0.016904  0.007145  0.000183  ...  0.015936  0.000000  0.009610   
1    0.018910  0.000000  0.008325  ...  0.000000  0.008859  0.038409   
2    0.037392  0.002476  0.008932  ...  0.007277  0.033581  0.012517   
3    0.030318  0.001422  0.000000  ...  0.006867  0.013808  0.010757   
4    0.051622  0.015592  0.000000  ...  0.017604  0.018369  0.010236   
..        ...       ...       ...  ...       ...       ...       ...   
495  0.046122  0.003150  0.006134  ...  0.000000  0.070910  0.031959   
496  0.013881  0.040206  0.000000  ...  0.000000  0.055083  0.040156   
497  0.013246  0.004865  0.000000  ...  0.031199  0.066593  0.001340   
498  0.007228  0.030524  0.006741  ...  0.067339  0.047755  0.057627   
499  0.031193  0.015491  0.006818  ...  0.007642  0.066700  0.030328   

         2041      2042      2043      2044      2045      2046      2047  
0    0.002775  0.025998  0.000000  0.008564  0.012472  0.027264  0.068992  
1    0.000000  0.012151  0.006759  0.038453  0.009979  0.023755  0.046499  
2    0.000000  0.008634  0.009804  0.059076  0.001408  0.000000  0.054350  
3    0.013188  0.000000  0.006450  0.037815  0.003467  0.033910  0.045657  
4    0.000000  0.020048  0.003556  0.043355  0.001706  0.020329  0.058333  
..        ...       ...       ...       ...       ...       ...       ...  
495  0.000000  0.000788  0.000000  0.017390  0.000000  0.000000  0.002118  
496  0.000000  0.015402  0.000000  0.017198  0.016880  0.000000  0.005811  
497  0.010760  0.004494  0.001959  0.009353  0.000000  0.039190  0.011286  
498  0.000000  0.002899  0.000000  0.050650  0.011020  0.018185  0.006826  
499  0.007844  0.000000  0.006438  0.074897  0.018137  0.020022  0.020733  

[500 rows x 2048 columns]

In [24]:
# call the knn algorithm for classification with vectorized
neighbors = NearestNeighbors(n_neighbors=6,algorithm='brute',metric='euclidean')
neighbors.fit(feature_list)
distances,indices = neighbors.kneighbors([normalized_result])

In [25]:
distances

array([[0.63758343, 0.6832639 , 0.7120415 , 0.72151166, 0.7333559 ,
        0.7404178 ]], dtype=float32)

In [28]:
indices

array([[22,  5, 13, 25, 40,  6]], dtype=int64)

In [30]:
indices[0][1:6]

array([ 5, 13, 25, 40,  6], dtype=int64)

In [32]:
for file in indices[0][1:6]:
    temp_img = cv2.imread(filenames[file])
    cv2.imshow('output',cv2.resize(temp_img,(512,512)))
    cv2.waitKey(0)